---
title: "Beta_diversity_by_time"
output: html_document
---

Bacterial abundance on the genus level<br>
-------------------------------------- 

<br>
Opening packages
```{r packages}
rm(list=ls())
setwd('~/Desktop/Projects/Project5_HV_Abx/20191202_Fig1_alldata')
#library (gplots) #library for graphics
#library (lattice) #library for multivariate graphics)
#library(RColorBrewer) #Provides colors according to a variable
#library(reshape) #Implies the functions melt and cast to restructure and aggregate data
library(ggplot2)
library(dplyr)
#library(nortest)
#library(stats)
#library(grid)
```
<br>

**Load data**
Input file: OTU based *.tax.summary file generated in mothur
```{r data}
table1 <- read.table('output_withHV.txt', sep="\t", header=T, stringsAsFactors=F)
table2 <- read.table('1118_output.txt', sep="\t", header=T, stringsAsFactors=F)

table <- merge(table1, table2, by="taxa", all=T)
colnames(table) <- gsub('(M\\w\\w\\d\\d\\d\\d).*', '\\1', colnames(table), ignore.case=T)
table[is.na(table)] <- 0
```

**File reading and manipulation**
```{r table opening and labeling fixing}
table <- data.frame(table, stringsAsFactors=F)
table <- table[table$taxa!='Totals',]

metadata <- read.table(file="meta_data.txt", sep="\t", header=T, stringsAsFactors=F)
metadata2 <- subset(metadata, !(Subject=='1042' & Treatment=='HV'))

sel_list <- metadata2$Sample[grep("Ac|Ra|Vf", metadata2$Site)]
#MET0368 is rerunning
sel_list <- sel_list[-c(grep('MET0368', sel_list))]

#sel_list <- sel_list[-c(grep('MET0320|MET0317', sel_list))]

#compromised <- read.table(file="compromised.txt", sep='\t', header=F, stringsAsFactors=F)
#compromised <- c(compromised$V1)
#sel_list <- sel_list[!sel_list %in% compromised]

table <- cbind(table$taxa, table[,colnames(table) %in% sel_list])
colnames(table)[1] <- 'taxa'
```
<br>

**Separating skin/oral**
```{r genus extraction}
#get raw counts
attach(table)
rownames(table) <- table$taxa

table_skin <- table[,2:ncol(table)]
```

**Skin**
```{r}
#Splitting table
table_skin <- table_skin[-grep('Escherichia_coli_BL21_Gold\\(DE3\\)pLysS_AG', rownames(table_skin)),]
bacterial_skin <- table_skin[grep("Bacteria;", rownames(table_skin)),]
fungal_skin <- table_skin[grep("Eukaryota;Fungi;", rownames(table_skin)),]
viral_skin <- table_skin[grep("Viruses;", rownames(table_skin)),]
others_skin <- table_skin[grep("Bacteria;|Eukaryota;Fungi;|Viruses;", rownames(table_skin), invert=TRUE),]

#Skin_bacteria
bacterial_skin$species <- gsub("(Bacteria;[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;[^;_]*_[^;_]*).*", "\\1", rownames(bacterial_skin))
bacterial_skin <- data.frame(bacterial_skin %>% group_by(species) %>% summarise_all(list(sum)))
rownames(bacterial_skin) <- bacterial_skin$species
bacterial_skin$species <- NULL

#Skin_Virus
viral_skin$species <- gsub("(Viruses;[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;[^;_]*_[^;_]*).*", "\\1", rownames(viral_skin))
viral_skin$species <- gsub("(Viruses;.*_phage).*", "\\1", viral_skin$species)
viral_skin <- data.frame(viral_skin %>% group_by(species) %>% summarise_all(list(sum)))
rownames(viral_skin) <- viral_skin$species
viral_skin$species <- NULL

#Skin_fungi
fungal_skin$species <- gsub("(Eukaryota;Fungi;[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;[^;_]*_[^;_]*).*", "\\1", rownames(fungal_skin))
fungal_skin <- data.frame(fungal_skin %>% group_by(species) %>% summarise_all(list(sum)))
rownames(fungal_skin) <- fungal_skin$species
fungal_skin$species <- NULL

#others and merge
skin_merged <- rbind(bacterial_skin, viral_skin, fungal_skin, colSums(others_skin[,]))
rownames(skin_merged)[nrow(skin_merged)] <- "Eukaryota;Others"

#colSums(skin_merged)
```


**Function for converting table into ratio**
```{r}
ratio_table <- function(df){
  return(data.frame(t(apply(df, 1, function(x){return(unlist(x/colSums(df)))})), stringsAsFactors=F))
}
```

**Beta diversity calculation and pcoa**
```{r}
library(vegan)
library(ape)

table_skin2 <- ratio_table(skin_merged)
#table_skin2 <- ratio_table(bacterial_skin)
#table_skin2 <- ratio_table(viral_skin)
#table_skin2 <- ratio_table(fungal_skin)
table_skin3 <- data.frame(t(table_skin2), stringsAsFactor=F)

metadata <- read.table(file="meta_data.txt", sep="\t", header=T, stringsAsFactors=F)

table_skin3$Site_info <- sapply(rownames(table_skin3), function(x){return(metadata$Site[grep(x, metadata$Sample)])})

table_skin_Ac <- subset(table_skin3, Site_info=="Ac-R")
table_skin_Ra <- subset(table_skin3, Site_info=="Ra-R")
table_skin_Vf <- subset(table_skin3, Site_info=="Vf-R")

table_skin_Ac$Site_info <- NULL
table_skin_Ra$Site_info <- NULL
table_skin_Vf$Site_info <- NULL

table_skin_Ac.D <- vegdist(table_skin_Ac, "jaccard", binary=T)
table_skin_Ra.D <- vegdist(table_skin_Ra, "jaccard", binary=T)
table_skin_Vf.D <- vegdist(table_skin_Vf, "jaccard", binary=T)

pcoa_Ac <- pcoa(table_skin_Ac.D)
pcoa_Ac_df <- data.frame(pcoa_Ac$vectors[,1:2], stringsAsFactors=F)
pcoa_Ra <- pcoa(table_skin_Ra.D)
pcoa_Ra_df <- data.frame(pcoa_Ra$vectors[,1:2], stringsAsFactors=F)
pcoa_Vf <- pcoa(table_skin_Vf.D)
pcoa_Vf_df <- data.frame(pcoa_Vf$vectors[,1:2], stringsAsFactors=F)
```
**theta distance**
```{r}
thetayc_calculator <- function(df){
  gop <- 0
  jegopcha <- 0
  for (i in 1:nrow(df)){
    gop <- gop+(df[i,1]*df[i,2])
    jegopcha <- jegopcha+((df[i,1]-df[i,2])^2)
  }
  thetayc <- 1-(gop/(jegopcha+gop))  
  return(thetayc)
}

theta_matrix <-  function(table_skin_t){
  theta_t <- NULL
  testt <- NULL
  for (j in 1:ncol(table_skin_t)){
    theta <- NULL
    for (i in 1:ncol(table_skin_t)){
      theta <- append(theta, thetayc_calculator(cbind(table_skin_t[,j], table_skin_t[,i])))
    }
    theta_t <- rbind(theta_t, theta)
  }
  skin_Ac_theta <- data.frame(theta_t, stringsAsFactors=F)
  colnames(skin_Ac_theta) <- colnames(table_skin_t)
  rownames(skin_Ac_theta) <- colnames(table_skin_t)
  a.dist <- as.dist(as(skin_Ac_theta, "matrix"))
  return(a.dist)
}

table_skin_Ac_t <- data.frame(t(table_skin_Ac), stringsAsFactors=F)
d.Ac <- theta_matrix(table_skin_Ac_t)
table_skin_Ra_t <- data.frame(t(table_skin_Ra), stringsAsFactors=F)
d.Ra <- theta_matrix(table_skin_Ra_t)
table_skin_Vf_t <- data.frame(t(table_skin_Vf), stringsAsFactors=F)
d.Vf <- theta_matrix(table_skin_Vf_t)

pcoa_Ac <- pcoa(d.Ac)
pcoa_Ac_df <- data.frame(pcoa_Ac$vectors[,1:2], stringsAsFactors=F)
pcoa_Ra <- pcoa(d.Ra)
pcoa_Ra_df <- data.frame(pcoa_Ra$vectors[,1:2], stringsAsFactors=F)
pcoa_Vf <- pcoa(d.Vf)
pcoa_Vf_df <- data.frame(pcoa_Vf$vectors[,1:2], stringsAsFactors=F)
```

** metadata addition **
```{r}
metadata_finder <- function(df, metadata){
  Subject <- NULL
  Site <- NULL
  Date <- NULL
  Treatment <- NULL
  for (i in rownames(df)){
    Subject <- append(Subject, metadata$Subject[grep(i, metadata$Sample)])
    Site <- append(Site, metadata$Site[grep(i, metadata$Sample)])
    Date <- append(Date, metadata$DateCollected[grep(i, metadata$Sample)])
    Treatment <- append(Treatment, metadata$Treatment[grep(i, metadata$Sample)])
  }
  df$Subject <- Subject
  df$Site <- Site
  df$Treatment <- Treatment
  df$Treatment <- factor(df$Treatment, levels=c('Doxy_20mg', 'Doxy_100mg', 'Cepha_500mg','TMP_SMX', 'HV'))
  df$Coll_date <- as.Date(Date, "%m/%d/%y")
  df$Sample_id <- rownames(df)
  df <- df %>% arrange(Coll_date) %>% arrange(Subject)
  return(df)
}
pcoa_Ac_df2 <- metadata_finder(pcoa_Ac_df, metadata)
pcoa_Ra_df2 <- metadata_finder(pcoa_Ra_df, metadata)
pcoa_Vf_df2 <- metadata_finder(pcoa_Vf_df, metadata)

#For 1050HV re-D0. manually change this!!!!
pcoa_Ac_df2 <- rbind(pcoa_Ac_df2, pcoa_Ac_df2[pcoa_Ac_df2$Sample_id=='MET0747',])
pcoa_Ac_df2 <- pcoa_Ac_df2 %>% arrange(Coll_date) %>% arrange(Subject)
pcoa_Ac_df2$Subject[60:61] <- paste(pcoa_Ac_df2$Subject[60:61], '_2', sep='')

pcoa_Ra_df2 <- rbind(pcoa_Ra_df2, pcoa_Ra_df2[pcoa_Ra_df2$Sample_id=='MET0743',])
pcoa_Ra_df2 <- pcoa_Ra_df2 %>% arrange(Coll_date) %>% arrange(Subject)
pcoa_Ra_df2$Subject[62:63] <- paste(pcoa_Ra_df2$Subject[62:63], '_2', sep='')

pcoa_Vf_df2 <- rbind(pcoa_Vf_df2, pcoa_Vf_df2[pcoa_Vf_df2$Sample_id=='MET0748',])
pcoa_Vf_df2 <- pcoa_Vf_df2 %>% arrange(Coll_date) %>% arrange(Subject)
pcoa_Vf_df2$Subject[59:60] <- paste(pcoa_Vf_df2$Subject[59:60], '_2', sep='')
###

DPI_calculator <- function(pcoa){
  ret_df <- NULL
  for (k in levels(factor(pcoa$Treatment))){
    sub_df <- pcoa[pcoa$Treatment==k,]
    i <- 2
    DPI <- 0
    DPI_Sum <- 0
    while (i<=dim(sub_df)[1]){
      if(sub_df$Subject[i]==sub_df$Subject[i-1]){
        DPI_Sum <- DPI_Sum+(sub_df$Coll_date[i]-sub_df$Coll_date[i-1])
        DPI <- append(DPI, DPI_Sum)
        i<-i+1
      } else {
        DPI <- append(DPI, 0)
        DPI_Sum <- 0
        i<-i+1
      }
    }
    sub_df <- cbind(sub_df, as.numeric(DPI))
    ret_df <- rbind(ret_df, sub_df)
  }
  colnames(ret_df)[ncol(ret_df)] <- 'DPI'
  ret_df <- ret_df %>% arrange(Coll_date) %>% arrange(Treatment) %>% arrange(Subject)
  return(ret_df)
}
#pcoa <- pcoa_Ra_df2
pcoa_Ac_df2 <- DPI_calculator(pcoa_Ac_df2)
pcoa_Ra_df2 <- DPI_calculator(pcoa_Ra_df2)
pcoa_Vf_df2 <- DPI_calculator(pcoa_Vf_df2)

D1_finder <- function(pcoa2){
  pcoa2$D1_sample <- "NULL"
  for (k in 1:nrow(pcoa2)){
    if (pcoa2$DPI[k]==0){
      pcoa2$D1_sample[k] <- pcoa2$Sample_id[k]
    }
    else {
      pcoa2$D1_sample[k] <- pcoa2$D1_sample[k-1]
    }
  }
  return(pcoa2)
}

pcoa_Ac_df2 <- D1_finder(pcoa_Ac_df2)
pcoa_Ra_df2 <- D1_finder(pcoa_Ra_df2)
pcoa_Vf_df2 <- D1_finder(pcoa_Vf_df2)

theta_from_df <- function(df, original_df){
  theta_value <- NULL
  for (i in 1:nrow(df)){
    theta_value <- append(theta_value,
                          thetayc_calculator(cbind(as.numeric(original_df[[df$Sample_id[i]]]), 
                                                   as.numeric(original_df[[df$D1_sample[i]]]))))
  }
  df <- cbind(df, theta_value)
  return(df)
}

pcoa_Ac_df3 <- theta_from_df(pcoa_Ac_df2, table_skin2)
pcoa_Ra_df3 <- theta_from_df(pcoa_Ra_df2, table_skin2)
pcoa_Vf_df3 <- theta_from_df(pcoa_Vf_df2, table_skin2)

#Ac
pcoa_Ac_df3_HV <- subset(pcoa_Ac_df3, Treatment=='HV')
pcoa_Ac_df3_HV_Doxy20 <- pcoa_Ac_df3_HV
pcoa_Ac_df3_HV_Doxy20$Subject <- gsub('(.*)', 'HV\\1', pcoa_Ac_df3_HV_Doxy20$Subject)
pcoa_Ac_df3_HV_Doxy20$Treatment <-'Doxy_20mg'
pcoa_Ac_df3_HV_Doxy100 <- pcoa_Ac_df3_HV
pcoa_Ac_df3_HV_Doxy100$Subject <- gsub('(.*)', 'HV\\1', pcoa_Ac_df3_HV_Doxy100$Subject)
pcoa_Ac_df3_HV_Doxy100$Treatment <-'Doxy_100mg'
pcoa_Ac_df3_HV_Cepha <- pcoa_Ac_df3_HV
pcoa_Ac_df3_HV_Cepha$Subject <- gsub('(.*)', 'HV\\1', pcoa_Ac_df3_HV_Cepha$Subject)
pcoa_Ac_df3_HV_Cepha$Treatment <-'Cepha_500mg'
pcoa_Ac_df3_HV_TMPSMX <- pcoa_Ac_df3_HV
pcoa_Ac_df3_HV_TMPSMX$Subject <- gsub('(.*)', 'HV\\1', pcoa_Ac_df3_HV_TMPSMX$Subject)
pcoa_Ac_df3_HV_TMPSMX$Treatment <-'TMP_SMX'
pcoa_Ac_df3 <- rbind(subset(pcoa_Ac_df3, Treatment!='HV'), pcoa_Ac_df3_HV_Doxy20, pcoa_Ac_df3_HV_Doxy100, pcoa_Ac_df3_HV_Cepha, pcoa_Ac_df3_HV_TMPSMX)

#Ra
pcoa_Ra_df3_HV <- subset(pcoa_Ra_df3, Treatment=='HV')
pcoa_Ra_df3_HV_Doxy20 <- pcoa_Ra_df3_HV
pcoa_Ra_df3_HV_Doxy20$Subject <- gsub('(.*)', 'HV\\1', pcoa_Ra_df3_HV_Doxy20$Subject)
pcoa_Ra_df3_HV_Doxy20$Treatment <-'Doxy_20mg'
pcoa_Ra_df3_HV_Doxy100 <- pcoa_Ra_df3_HV
pcoa_Ra_df3_HV_Doxy100$Subject <- gsub('(.*)', 'HV\\1', pcoa_Ra_df3_HV_Doxy100$Subject)
pcoa_Ra_df3_HV_Doxy100$Treatment <-'Doxy_100mg'
pcoa_Ra_df3_HV_Cepha <- pcoa_Ra_df3_HV
pcoa_Ra_df3_HV_Cepha$Subject <- gsub('(.*)', 'HV\\1', pcoa_Ra_df3_HV_Cepha$Subject)
pcoa_Ra_df3_HV_Cepha$Treatment <-'Cepha_500mg'
pcoa_Ra_df3_HV_TMPSMX <- pcoa_Ra_df3_HV
pcoa_Ra_df3_HV_TMPSMX$Subject <- gsub('(.*)', 'HV\\1', pcoa_Ra_df3_HV_TMPSMX$Subject)
pcoa_Ra_df3_HV_TMPSMX$Treatment <-'TMP_SMX'
pcoa_Ra_df3 <- rbind(subset(pcoa_Ra_df3, Treatment!='HV'), pcoa_Ra_df3_HV_Doxy20, pcoa_Ra_df3_HV_Doxy100, pcoa_Ra_df3_HV_Cepha, pcoa_Ra_df3_HV_TMPSMX)

#Vf
pcoa_Vf_df3_HV <- subset(pcoa_Vf_df3, Treatment=='HV')
pcoa_Vf_df3_HV_Doxy20 <- pcoa_Vf_df3_HV
pcoa_Vf_df3_HV_Doxy20$Subject <- gsub('(.*)', 'HV\\1', pcoa_Vf_df3_HV_Doxy20$Subject)
pcoa_Vf_df3_HV_Doxy20$Treatment <-'Doxy_20mg'
pcoa_Vf_df3_HV_Doxy100 <- pcoa_Vf_df3_HV
pcoa_Vf_df3_HV_Doxy100$Subject <- gsub('(.*)', 'HV\\1', pcoa_Vf_df3_HV_Doxy100$Subject)
pcoa_Vf_df3_HV_Doxy100$Treatment <-'Doxy_100mg'
pcoa_Vf_df3_HV_Cepha <- pcoa_Vf_df3_HV
pcoa_Vf_df3_HV_Cepha$Subject <- gsub('(.*)', 'HV\\1', pcoa_Vf_df3_HV_Cepha$Subject)
pcoa_Vf_df3_HV_Cepha$Treatment <-'Cepha_500mg'
pcoa_Vf_df3_HV_TMPSMX <- pcoa_Vf_df3_HV
pcoa_Vf_df3_HV_TMPSMX$Subject <- gsub('(.*)', 'HV\\1', pcoa_Vf_df3_HV_TMPSMX$Subject)
pcoa_Vf_df3_HV_TMPSMX$Treatment <-'TMP_SMX'
pcoa_Vf_df3 <- rbind(subset(pcoa_Vf_df3, Treatment!='HV'), pcoa_Vf_df3_HV_Doxy20, pcoa_Vf_df3_HV_Doxy100, pcoa_Vf_df3_HV_Cepha, pcoa_Vf_df3_HV_TMPSMX)


pcoa_Ac_df3$period <- ifelse(grepl('Doxy', pcoa_Ac_df3$Treatment), 56, 14)
pcoa_Ac_df3$Subject <- factor(pcoa_Ac_df3$Subject, levels=c(rev(levels(factor(pcoa_Ac_df3$Subject)))))
pcoa_Ac_df3$Treatment2 <- ifelse(grepl('HV', pcoa_Ac_df3$Subject), 'HV', as.character(pcoa_Ac_df3$Treatment))
pcoa_Ac_df3$Treatment2 <- factor(pcoa_Ac_df3$Treatment2, 
                                 levels=c('Doxy_20mg', 'Doxy_100mg', 'Cepha_500mg', 'TMP_SMX','HV'))

pcoa_Ra_df3$period <- ifelse(grepl('Doxy', pcoa_Ra_df3$Treatment), 56, 14)
pcoa_Ra_df3$Subject <- factor(pcoa_Ra_df3$Subject, levels=c(rev(levels(factor(pcoa_Ra_df3$Subject)))))
pcoa_Ra_df3$Treatment2 <- ifelse(grepl('HV', pcoa_Ra_df3$Subject), 'HV', as.character(pcoa_Ra_df3$Treatment))
pcoa_Ra_df3$Treatment2 <- factor(pcoa_Ra_df3$Treatment2, 
                                 levels=c('Doxy_20mg', 'Doxy_100mg', 'Cepha_500mg', 'TMP_SMX','HV'))

pcoa_Vf_df3$period <- ifelse(grepl('Doxy', pcoa_Vf_df3$Treatment), 56, 14)
pcoa_Vf_df3$Subject <- factor(pcoa_Vf_df3$Subject, levels=c(rev(levels(factor(pcoa_Vf_df3$Subject)))))
pcoa_Vf_df3$Treatment2 <- ifelse(grepl('HV', pcoa_Vf_df3$Subject), 'HV', as.character(pcoa_Vf_df3$Treatment))
pcoa_Vf_df3$Treatment2 <- factor(pcoa_Vf_df3$Treatment2, 
                                 levels=c('Doxy_20mg', 'Doxy_100mg', 'Cepha_500mg', 'TMP_SMX','HV'))
```

**Plotting**
```{r}
rect_table <- data.frame(cbind(c('Doxy_20mg', 'Doxy_100mg', 'Cepha_500mg', 'TMP_SMX'),
                    c(56, 56, 14, 14)), stringsAsFactors=F)
colnames(rect_table) <- c('Treatment', 'period')
rect_table$Treatment <- factor(rect_table$Treatment,
                               levels=c('Doxy_20mg', 'Doxy_100mg', 'Cepha_500mg', 'TMP_SMX','HV'))

library(scales)
library(RColorBrewer)
pdf(file="Ac_PCoA_theta_kinetics_withHV_allkingdom.pdf", height=6, width=5, useDingbats=F)
ggplot(pcoa_Ac_df3) +
  geom_rect(data=rect_table, aes(xmin=0, xmax=as.numeric(period), ymin=-Inf, ymax=Inf), fill="black", alpha=0.05) +
  geom_point(aes(x=DPI, y=theta_value, group=Subject, color=Treatment2), alpha=1, size=1) + 
  geom_line(aes(x=DPI, y=theta_value, group=Subject, color=Treatment2), alpha=0.75) + 
  scale_color_manual(values=c(brewer.pal(4, 'Set1')[c(3,1,4,2)], 'grey30')) +
#  scale_color_manual(values=c(hue_pal()(13), 'grey', 'grey', 'grey', 'grey', 'grey', 'grey')) + 
  facet_wrap(~Treatment, nrow=4) +
  theme_bw()
dev.off()

pdf(file="Ra_PCoA_theta_kinetics_withHV_allkingdom.pdf", height=6, width=5, useDingbats=F)
ggplot(pcoa_Ra_df3) +
  geom_rect(data=rect_table, aes(xmin=0, xmax=as.numeric(period), ymin=-Inf, ymax=Inf), fill="black", alpha=0.05) +
  geom_point(aes(x=DPI, y=theta_value, group=Subject, color=Treatment2), alpha=1, size=1) + 
  geom_line(aes(x=DPI, y=theta_value, group=Subject, color=Treatment2), alpha=0.75) + 
  scale_color_manual(values=c(brewer.pal(4, 'Set1')[c(3,1,4,2)], 'grey30')) +
#  scale_color_manual(values=c(hue_pal()(13), 'grey', 'grey', 'grey', 'grey', 'grey', 'grey')) + 
  facet_wrap(~Treatment, nrow=4) +
  theme_bw()
dev.off()

pdf(file="Vf_PCoA_theta_kinetics_withHV_allkingdom.pdf", height=6, width=5, useDingbats=F)
ggplot(pcoa_Vf_df3) +
  geom_rect(data=rect_table, aes(xmin=0, xmax=as.numeric(period), ymin=-Inf, ymax=Inf), fill="black", alpha=0.05) +
  geom_point(aes(x=DPI, y=theta_value, group=Subject, color=Treatment2), alpha=1, size=1) + 
  geom_line(aes(x=DPI, y=theta_value, group=Subject, color=Treatment2), alpha=0.75) + 
  scale_color_manual(values=c(brewer.pal(4, 'Set1')[c(3,1,4,2)], 'grey30')) +
#  scale_color_manual(values=c(hue_pal()(13), 'grey', 'grey', 'grey', 'grey', 'grey', 'grey')) + 
  facet_wrap(~Treatment, nrow=4) +
  theme_bw()
dev.off()
```
